title = "League Stat Tracker"
timestamp = 1729989247376
summary = "My adventure in creating a stat tracker for league of legends"
content = "projects/league-stat/content.md"
image = "/assets/lilith.jpg"
