title = "Tracking players on League of Legends"
timestamp = 1
summary = "My personal endeavour to create a tracker that allows me to better effectively flame my friends :3"
content = "projects/league/content.md"
